name: Run Server and Tests

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Step 1: Build images
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Step 2: Create containers
      - name:  Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d
          
      # Step 3: Enter in backend container and run api tests
      - name: Enter Docker Container and run tests
        run: |
          CONTAINER_ID=$(docker-compose -f docker-compose.yml ps -q instagram-backend-instance)
          docker exec -it $CONTAINER_ID bash -c "cd ./backend && npm install && npm run test"

