name: Run Server and Tests

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Step 1: Build images
      - name: Build Docker images
        run: |
          docker-compose build

      # Step 2: Create containers
      - name:  Start Docker Compose services
        run: |
          docker-compose up -d
          
      # Step 3: Enter in backend container and run api tests
      - name: Enter Docker Container and run tests
        run: |
          CONTAINER_ID=$(docker-compose ps -q instagram-backend)
          docker exec -it $CONTAINER_ID bash -c "npm install && npm run test"

