name: API Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change directory to backend
        run: cd ./backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version needed for your project

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      # Optionally, you can include steps to publish test results or artifacts
      # For example, to publish test coverage reports:
      # - name: Upload coverage report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-report
      #     path: path/to/coverage/report

      # - name: Publish coverage report
      #   uses: actions/codecov@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}  # Replace with your Codecov token
