name: Docker Compose CI/CD

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Compose services
      run: docker-compose build

    - name: Run Docker Compose services
      run: docker-compose up -d
